#!/bin/bash
cd "${0%/*}" || exit # Run from this directory

#------------------------------------------------------------------------------

source ./buildCommands

#------------------------------------------------------------------------------

WCleanDir libUtils
WCleanDir libFarField
WCleanDir farFieldFoam

#------------------------------------------------------------------------------